In [1]:
import numpy as np


In [2]:
l=[1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
np.zeros((3,4,5,2,4))

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

        

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [13]:
np.empty((4,5))

array([[0.00000000e+000, 2.14321575e-312, 2.44029516e-312,
        2.31297541e-312, 2.33419537e-312],
       [2.44029516e-312, 2.05833592e-312, 2.05833592e-312,
        2.12199579e-312, 2.29175545e-312],
       [2.35541533e-312, 2.46151512e-312, 2.05833592e-312,
        2.05833592e-312, 2.35541533e-312],
       [2.12199579e-312, 1.08221785e-312, 2.07955588e-312,
        2.33419537e-312, 0.00000000e+000]])

In [16]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [17]:
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [18]:
np.linspace(2,6,100)

array([2.        , 2.04040404, 2.08080808, 2.12121212, 2.16161616,
       2.2020202 , 2.24242424, 2.28282828, 2.32323232, 2.36363636,
       2.4040404 , 2.44444444, 2.48484848, 2.52525253, 2.56565657,
       2.60606061, 2.64646465, 2.68686869, 2.72727273, 2.76767677,
       2.80808081, 2.84848485, 2.88888889, 2.92929293, 2.96969697,
       3.01010101, 3.05050505, 3.09090909, 3.13131313, 3.17171717,
       3.21212121, 3.25252525, 3.29292929, 3.33333333, 3.37373737,
       3.41414141, 3.45454545, 3.49494949, 3.53535354, 3.57575758,
       3.61616162, 3.65656566, 3.6969697 , 3.73737374, 3.77777778,
       3.81818182, 3.85858586, 3.8989899 , 3.93939394, 3.97979798,
       4.02020202, 4.06060606, 4.1010101 , 4.14141414, 4.18181818,
       4.22222222, 4.26262626, 4.3030303 , 4.34343434, 4.38383838,
       4.42424242, 4.46464646, 4.50505051, 4.54545455, 4.58585859,
       4.62626263, 4.66666667, 4.70707071, 4.74747475, 4.78787879,
       4.82828283, 4.86868687, 4.90909091, 4.94949495, 4.98989

In [20]:
np.linspace(2,6,10).reshape(2,5)

array([[2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778],
       [4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ]])

In [21]:
np.linspace(2,6,10).reshape(5,2)

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [22]:
np.linspace(2,6,10,endpoint=False).reshape(5,2)

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [24]:
np.linspace(2,6,10,endpoint=False,retstep=True)

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [27]:
np.logspace(2,5) #gives log numbers spaces

array([   100.        ,    115.13953993,    132.57113656,    152.64179672,
          175.75106249,    202.35896477,    232.99518105,    268.26957953,
          308.88435965,    355.64803062,    409.49150624,    471.48663635,
          542.86754393,    625.05519253,    719.685673  ,    828.64277285,
          954.09547635,   1098.54114199,   1264.85521686,   1456.3484775 ,
         1676.83293681,   1930.69772888,   2222.99648253,   2559.5479227 ,
         2947.05170255,   3393.2217719 ,   3906.93993705,   4498.43266897,
         5179.47467923,   5963.62331659,   6866.48845004,   7906.04321091,
         9102.98177992,  10481.13134155,  12067.92640639,  13894.95494373,
        15998.58719606,  18420.69969327,  21209.5088792 ,  24420.53094549,
        28117.68697974,  32374.57542818,  37275.93720315,  42919.34260129,
        49417.13361324,  56898.66029018,  65512.85568596,  75431.20063355,
        86851.13737514, 100000.        ])

In [28]:
np.logspace(2,4,10,base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [31]:
np.logspace(2,4,10,base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [35]:
a=np.arange(2,8)

In [36]:
a

array([2, 3, 4, 5, 6, 7])

In [43]:
a=np.arange(4,20).reshape(4,4)

In [44]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
a.max()

19

In [46]:
a.min()

4

In [49]:
a=np.arange(4,40).reshape(3,6,2)

In [50]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [51]:
a.max()

39

In [52]:
a.max(axis=1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [53]:
a.max(axis=0)

array([[28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [55]:
a=np.arange(4,40).reshape(6,6)

In [56]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [57]:
a.max(axis=0)

array([34, 35, 36, 37, 38, 39])

In [58]:
a.max(axis=1)

array([ 9, 15, 21, 27, 33, 39])

In [63]:
a=np.array([4,5,6])

In [64]:
a

array([4, 5, 6])

In [65]:
a.max()

6

In [69]:
a=np.array([[4,5,6],[8,4,5]])

In [70]:
a.max()

8

In [71]:
a.max(0)

array([8, 5, 6])

In [72]:
a.max(1)

array([6, 8])

In [73]:
10+a

array([[14, 15, 16],
       [18, 14, 15]])

In [75]:
a/0 #gives warning

/var/folders/fs/g85qz5d176sgvl77v6b51nmw0000gn/T/ipykernel_84686/9201251.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0 #gives warning


array([[inf, inf, inf],
       [inf, inf, inf]])

In [76]:
a**2

array([[16, 25, 36],
       [64, 16, 25]])

In [77]:
pow(a,2)

array([[16, 25, 36],
       [64, 16, 25]])

In [78]:
pow(a,3)

array([[ 64, 125, 216],
       [512,  64, 125]])

In [79]:
b=[2,3,1,2,3]

In [85]:
b=np.array([2,3,1,2,3,5])

In [86]:
b

array([2, 3, 1, 2, 3, 5])

In [90]:
a=np.arange(4,40).reshape(6,6)
a


array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [89]:
a+b #broadcasting operation

array([[ 6,  8,  7,  9, 11, 14],
       [12, 14, 13, 15, 17, 20],
       [18, 20, 19, 21, 23, 26],
       [24, 26, 25, 27, 29, 32],
       [30, 32, 31, 33, 35, 38],
       [36, 38, 37, 39, 41, 44]])

In [91]:
b=np.array([2,3,1,2,3,5]).T

In [92]:
b

array([2, 3, 1, 2, 3, 5])

In [98]:
b.reshape(1,-1)

array([[2, 3, 1, 2, 3, 5]])

In [95]:
b.T+a

array([[ 6,  8,  7,  9, 11, 14],
       [12, 14, 13, 15, 17, 20],
       [18, 20, 19, 21, 23, 26],
       [24, 26, 25, 27, 29, 32],
       [30, 32, 31, 33, 35, 38],
       [36, 38, 37, 39, 41, 44]])

In [93]:
a+b

array([[ 6,  8,  7,  9, 11, 14],
       [12, 14, 13, 15, 17, 20],
       [18, 20, 19, 21, 23, 26],
       [24, 26, 25, 27, 29, 32],
       [30, 32, 31, 33, 35, 38],
       [36, 38, 37, 39, 41, 44]])

In [96]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [99]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [100]:
x=np.asarray([1,2,3])

In [101]:
y=x

In [102]:
y

array([1, 2, 3])

In [103]:
z=np.copy(x) #deepcopy

In [104]:
z

array([1, 2, 3])

In [105]:
x[0]=100   #deepcopy

In [107]:
y  #deepcopy

array([100,   2,   3])

In [108]:
z=np.copy(x)

In [110]:
z #shallow copy

array([100,   2,   3])

In [111]:
x[0]=90 

In [112]:
x

array([90,  2,  3])

In [113]:
z #shallow copy

array([100,   2,   3])

In [116]:
id(x[0]) #location 

140444902197648

In [117]:
id(x)

140444902097712

In [118]:
id(y) #same as x

140444902097712

In [119]:
id(x[1])

140444902198096

In [120]:
id(y[1])

140444902197648

In [121]:
id(z[1])

140444902198256

In [123]:
su=np.array([567,345])

In [124]:
df=su

In [125]:
id(df)

140444902182320

In [126]:
id(su)

140444902182320

In [132]:
id(su)==id(df)

True

In [127]:
id(df[0])

140444902198480

In [128]:
id(df[0])

140444902197648

In [129]:
id(df[0])==id(df[0])

True

In [130]:
id(df[0])==id(df[1])

True

In [133]:
xt=np.array([34,67,89])

In [134]:
id(xt[0])==id(su[0])

True

In [135]:
c="sudh"

In [136]:
id(c)

140443820426288

In [137]:
id(c[0])

140444625524912

In [139]:
id(c)==id(su[0])

False

In [140]:
su

array([567, 345])